# NumPy 미니퀘스트

In [2]:
import numpy as np

## 차원

In [5]:
# 1번 퀘스트
# 다음 NumPy 배열의 차원 수를 출력하는 코드를 작성하기
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array.ndim)

3


In [6]:
# 2번 퀘스트
# 1차원 배열을 2차원 배열로 반환하여 (2, 3) 형태로 출력하기
array = np.array([10, 20, 30, 40, 50, 60])
reshaped_array = array.reshape(2, 3)
print(reshaped_array)

[[10 20 30]
 [40 50 60]]


In [10]:
# 3번 퀘스트
# 다음 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 반환하고,
# 최종 배열의 차원 수를 출력하기
    # nexaxis를 사용해 배열의 차원 추가
    # 새로운 차원에서 배열 모양을 확인한 후 최종 차원 수 출력
array = np.array([7, 14, 21])
reshaped_array = array.reshape(3, 1)
newaxis = reshaped_array.ndim
print(reshaped_array)
print(newaxis) # 2, 2차원

[[ 7]
 [14]
 [21]]
2


## Shape

In [12]:
# 1번 퀘스트
# 주어진 2차원 배열의 형태(Shape)를 출력하는 코드 작성하기
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)

(2, 3)


In [13]:
# 2번 퀘스트
# 1차원 배열을 (2, 3) 형태로 변경한 후,
# 새로운 배열의 형태를 출력하기
array = np.array([10, 20, 30, 40, 50, 60])
reshaped_array = array.reshape(2, 3)
print(reshaped_array)

[[10 20 30]
 [40 50 60]]


In [17]:
# 3번 퀘스트
# 다음 3차원 배열의 형태를 (3, 2, 2) 형태로 변경하고
# 최종 배열의 형태를 출력하기
array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
reshaped_array = array.reshape(3, 2, 2)
print(reshaped_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## 데이터 타입

In [27]:
# 1번 퀘스트
# 아래의 배열의 데이터 타입을 확인하기
array = np.array([10, 20, 30])
print(array.dtype)
print(array.itemsize)
print(array.nbytes)

int64
8
24


In [ ]:
# 2번 퀘스트
# 정수형 배열을 부동소수점형 배열로 변환하고,
# 변환된 배열의 데이터 타입을 출력하는 코드를 작성하기

# 방법 1. 바로 타입 변환
array = np.array([1, 2, 3], dtype=np.float64)
print(array.dtype)

# 방법 2. 명시적으로 타입 변환
# array = np.array([1, 2, 3])
# converted_array = array.astype(np.float64) # 명시적
# print(converted_array.dtype)

float64


In [ ]:
# 3번 퀘스트
# 배열을 uint8로 변환한 후, 메모리 사용량(바이트)를 출력하기

# 방법 1. (OverflowError 발생) 엄격한 검사 후 변환(strict check)
# array = np.array([100, 200, 300], dtype=np.int8)
# print(array.itemsize)
# print(array.nbytes)

# 방법 2. 안전한 타입 int64로 만들고, 변환
array = np.array([100, 200, 300])
converted_array = array.astype(np.uint8)
print(converted_array) # [100, 200, 44]
print(converted_array.itemsize)
print(converted_array.nbytes)


[100 200  44]
1
3


### (NumPy의 설계 의도) dtype 지정 시 주의사항
- `np.uint8`은 0~255까지만 저장할 수 있는 타입(1바이트)

1. (방법 1) 생성 시점저에 값을 넣을 때
  - NumPy는 이 값이 정말 uint8에 들어갈 수 있는지 엄격히 검사
  - 300은 uint8 범위를 벗어나기 떄문에 OverflowError로 데이터 손실을 미리 막아줌
2. (방법 2) 나중에 변환할 떄
  - 기본 동작이 `casting='unsafe'` (안전하지 않은 허용)
  - 범위를 벗어나는 값은 자동으로 wrap around(Modulo 256) 처리
  - 300 % 256 = 44가 된다.

## 인덱싱

In [42]:
# 1번 퀘스트
# 주어진 배열에서 첫 번째 요소와 마지막 요소를 출력하기
array = np.array([10, 20, 30, 40, 50])
first_element = array[0]
last_element = array[-1]
print(first_element, last_element)

10 50


In [44]:
# 2번 퀘스트
# 첫 번째 열과 두 번째 행을 출력하기
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
first_column = matrix[:, 0]
second_row = matrix[1]
print(f"first_column: {first_column}")
print(f"second_row: {second_row}")

first_column: [1 4 7]
second_row: [4 5 6]


In [50]:
# 3번 퀘스트
# 주어진 배열에서 10보다 큰 요소만 선택하고,
# 해당 요소의 인덱스를 출력하기
array = np.array([5, 15, 8, 20, 3, 12])
indices = np.where(array > 10)[0]
print(array[indices])

[15 20 12]


### 요소들의 인덱스 출력하기
- `np.where(조건)[0]`
    - `np.where(조건)`는 항상 튜플로 인덱스 조회
    - `[0]`: 인덱스만 사용하고 싶을 때, where에서 실제 배열 꺼냄.

## 연산

In [56]:
# 1번 퀘스트
# 주어진 배열에서 요소별(Element-wise) 덧셈 수행하기
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a, b))
# print(np.subtract(a, b))
# print(np.multiply(a, b))
# print(np.divide(a, b))

[5 7 9]


In [ ]:
# 2번 퀘스트
# 다음 배열에서 브로드캐스팅을 활용하여
# 각 행에 [1, 2, 3]을 더하기
matrix = np.array([[10, 20, 30], [40, 50, 60]]) # (2, 1)
array = np.array([1, 2, 3]) # (3,)
print(matrix + array)

# matrix = np.array([[10], [40]]) # (2, 1)
# array2 = np.array([[1, 2, 3]]) # (1, 3)
# print(matrix.shape)
# print(array2.shape)
# print(matrix + array2)

(3,)
[[11 22 33]
 [41 52 63]]


### 브로드캐스팅 규칙
- 배열의 모양을 마지막 축부터 맞춘다.
- 각 축에서 두 크기가 같거나 한쪽이 1이면 연산 가능하다.
- 모자란 축은 길이 1로 있다고 간주해 값이 복제된다.
    - 이 때 결과 shape은 각 축별로 더 큰 값을 선택한다.
- 예시
    - `(2, 3) + (1, 3) -> (2, 3)`
    - `(2, 1) + (1, 3) -> (2, 3)`
        - 행이 맞지 않지만 1이라 확장 가능
    - `(2, 3) + Scalar -> (2, 3)`
        - 스칼라는 모든 위치로 브로드캐스트 가능
    - `(2, 3) + (3, 2) -> X`
        - 마지막 축도 다르고
        - 서로 1도 아니고
        - 같지도 않음
        - 오류 반환

In [75]:
# 3번 퀘스트
# 주어진 배열에 대해 축을 기준으로 최댓값을 구하고
# 최종 배열의 차원을 출력하기
array = np.array([[3, 7, 2], [8, 4, 6]])
print(array.ndim)

# 행(row) 기준 최대값
print(np.max(array, axis=1))
# 열(col) 기준 최대값
print(np.max(array, axis=0))

2
[7 8]
[8 7 6]


## 유니버셜 함수

In [76]:
# 1번 퀘스트
# 배열에 대해 유니버셜 함수를 사용하여
# 모든 요소를 제곱한 결과 출력하기
array = np.array([1, 2, 3, 4])
print(np.power(array, 2))

[ 1  4  9 16]


In [78]:
# 2번 퀘스트
# 다음 두 배열의 요소별 합을 계산하고
# 결과를 기존 배열에 저장하기
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])
result = np.empty_like(array1)
np.add(array1, array2, out=result)
print(result)

[11 22 33]


In [80]:
# 3번 퀘스트
# 다음 배열에 유니버셜 함수를 사용하여
# 요소별 자연로그(log)를 계산하고
# 특정 조건을 만족하는 요소만 출력하기 (log 값 > 1)
array = np.array([1, np.e, 10, 100])
print(np.log(array))
print(array[np.log(array) > 1])

[0.         1.         2.30258509 4.60517019]
[ 10. 100.]
